id: adversary
name: Adversary Emulation Workshop
description: |
  Basics of setting up and using Operator to perform basic adversary emulation tasks and investigating how that can be used
  to create a continuous defensive evaluation process.
courses:
  - name: Offensive Infrastructure
    description: Basic concepts of offensive tools and infrastructure design
    challenges:
      - 387063c1-076e-4405-b5bc-455a4c9658a2
      - f15c367c-d966-480f-91dd-2f46841f490d
  - name: Using Operator
    description: Basic concepts of Operator
    challenges:
      - 70408815-c06a-44ff-a2b7-84d94885dd30
      - 2a729508-8410-4ea8-924d-a6ddd14fd64d
      - 2f801418-a956-43cc-8a21-504c0ce5b602
      - 8fb4c5f2-2be1-4f54-a330-061992cc8a4f
      - 9a6caab1-13a1-4b44-9eb4-b4994d860863
      - d4309b3b-3a43-462f-9f38-520e3890697e
  - name: Threat Modeling
    description: Understanding relevant threats to your organization
    challenges:
      - e979d382-9b90-4c89-b803-51ff721d7433
  - name: Building your adversary
    description: Design and build your own adversary
    challenges:
      - 0b044323-bf6b-4856-8d70-372942983aab
      - 2aac8660-191d-4617-a0b4-a02de8d19364
      - 4f936586-dbfa-41e0-9df4-540c7ce9d9e2
      - 9112f8d6-4ee1-4582-bd55-d42519cec783
      - c8bfb952-828a-4331-8395-13fee2faf47d
  - name: Running your engagement
    description: Launch your engagement
    challenges:
      - 289185c5-6a5e-4693-a613-c67239db7a6e
  - name: Process improvement
    description: Building a process improvement cycle
    challenges:
      - abc8fc70-2503-4764-904b-e81d998166e5