id: adversary
name: Adversary Emulation
description: |
  Basics of setting up and using Operator to perform basic adversary emulation tasks and investigating how that can be used
  to create a continuous defensive evaluation process.
courses:
  - name: Offensive Infrastructure
    description: blah
    challenges:
      - 387063c1-076e-4405-b5bc-455a4c9658a2
  - name: Threat Modeling
    description: blah
    challenges:
      - e979d382-9b90-4c89-b803-51ff721d7433
  - name: Using Operator
    description: blah
    challenges:
      - 70408815-c06a-44ff-a2b7-84d94885dd30
  - name: Building your adversary
    description: blah
    challenges:
      - 4f936586-dbfa-41e0-9df4-540c7ce9d9e2
  - name: Running your engagement
    description: blah
    challenges:
      - 289185c5-6a5e-4693-a613-c67239db7a6e
  - name: Process improvement
    description: blah
    challenges:
      - abc8fc70-2503-4764-904b-e81d998166e5